### ISSUE TITLE
sdfont_generator crash

### ISSUE THREAD

**Issue by Franticware** [ShoYamanishi/SDFont#3]
`sdfont_generator -verbose -font_path Tuffy-Bold.ttf -max_code_point 127 -texture_size 512 texture`
crashes in Generator::generateTexture - at one point, dstY is negative.

It works with -texture_size 256

The font is this one: https://www.dafont.com/tuffy.font

**Comment by ShoYamanishi** [comment]
Ok. Thanks for reporting. Let me take a look...

**Comment by ShoYamanishi** [comment]
Sorry for belated response. I could not get hold of a Linux machine but I'm now able to reproduce the problem on M1 Mac.

* Problem reproduced on Mac OSX w/o OpenGL.
```
SDFont % ./bin/sdfont_generator -verbose -font_path ../../SDFont/improved_version/Tuffy-Bold.ttf -max_code_point 127 -texture_size 512 texture_512
...............................
...............................
...............................
...............................
...............................
...............................
...............................
..........****.................
.........******................
.......*********.......*.......
.......***********....**.......
.......*****************.......
.......*****************.......
.......*****************.......
.......***....**********.......
.......*.......*********.......
................*******........
..................***..........
...............................
...............................
...............................
...............................
...............................
...............................
95/95
Base:[194 , 461]

zsh: segmentation fault  ./bin/sdfont_generator -verbose -font_path  -max_code_point 127 -texture_size
```

* Cause
The variable dstY in Generator::generateTexture() becomes out of range due to numerical drift at some edge cases.

* Solution
Add extra boundary checks to Generator::generateTexture()
